### ISSUE TITLE
Use Clipping in the Page Manager?

### ISSUE THREAD

**Issue by meghead** [suragch/streaming_audio_flutter_demo#2]
Before using your page manager to manage the slider, I was using this code in order to clip a fixed amount from the end of playback;
 
 ```
await _audioPlayer.setUrl(url!);

_audioPlayer.durationStream.first.then((event) {
      if(event != null){
        int newevent;
        newevent = event.inMilliseconds - 100;
        _audioPlayer.setClip(start: Duration(milliseconds: 0), end: Duration(milliseconds: newevent));
      }
    }
```

But this code seems to interfere with your slider.

Is there a better way to use clipping within your page manager?

**Comment by suragch** [comment]
The slider needs a total time and a progress to that time. Both of these values would need to be recalculated for a clip. 

In your example, though, the clip appears to be the total duration, so I don't know what the problem is. Can you explain it in more detail?

**Comment by suragch** [comment]
Since I haven't heard anything more about this recently I'll close this issue for now.
